apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: boa-ekibi
  description: BOA geliştirme ekibi
spec:
  type: team
  profile:
    displayName: BOA Ekibi
    email: Squad-EnterpriseArchitecture-BOA@architecht.com
  children: []
